/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.beingprogrammer.spritesheetmaker;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class View extends javax.swing.JFrame {

    BackView backView;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        backView = new BackView(this);
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        getRawFolder = new javax.swing.JButton();
        setRawFolder = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        spriteDemoPanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        colorPadding = new javax.swing.JButton();
        colorSprite = new javax.swing.JButton();
        spriteImageToggle = new javax.swing.JToggleButton();
        finalSpritePanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        colorMargin = new javax.swing.JButton();
        colorPadding1 = new javax.swing.JButton();
        colorSprite1 = new javax.swing.JButton();
        spriteDemoPanel2 = new javax.swing.JPanel();
        spriteSheetImageToggle = new javax.swing.JToggleButton();
        sourceSpritePanel = new javax.swing.JPanel();
        sourceSpriteViewPanel = new javax.swing.JPanel();
        finalSpriteSheetPanel = new javax.swing.JPanel();
        finalSpriteViewPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getPaddingRight = new javax.swing.JFormattedTextField();
        getPaddingBottom = new javax.swing.JFormattedTextField();
        getPaddingLeft = new javax.swing.JFormattedTextField();
        getPaddingTop = new javax.swing.JFormattedTextField();
        paddingType = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        getSpriteHeight = new javax.swing.JFormattedTextField();
        getSpriteWidth = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        setTotalSprites = new javax.swing.JFormattedTextField();
        setSpritesheetWidth = new javax.swing.JFormattedTextField();
        getSpriteRow = new javax.swing.JFormattedTextField();
        getSpriteSpaceLeft = new javax.swing.JFormattedTextField();
        getSpriteSpaceRight = new javax.swing.JFormattedTextField();
        setSpritesheetHeight = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        getImageType = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        setSourceFolder = new javax.swing.JLabel();
        getSourceFolder = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        setGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        setSourceFiles = new javax.swing.JList();
        delItem = new javax.swing.JButton();
        applySprite = new javax.swing.JButton();
        preview = new javax.swing.JButton();
        openRawFolder = new javax.swing.JButton();
        addFile = new javax.swing.JButton();
        clearFiles = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel22 = new javax.swing.JLabel();
        importType = new javax.swing.JComboBox();
        spriteSheetCheckBox = new javax.swing.JCheckBox();
        finalSpriteSheetCheckBox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAddFromFolder = new javax.swing.JMenuItem();
        menuAddFile = new javax.swing.JMenuItem();
        menuLoadOldFiles = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuEditFileProperties = new javax.swing.JMenuItem();
        menuToggleImageType = new javax.swing.JMenuItem();
        menuTogglePaddingType = new javax.swing.JMenuItem();
        menuToggleImportType = new javax.swing.JMenuItem();
        menuRemoveFile = new javax.swing.JMenuItem();
        menuClearAllFile = new javax.swing.JMenuItem();
        menuShowImage = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuApplyToSprite = new javax.swing.JMenuItem();
        menuPriview = new javax.swing.JMenuItem();
        menuGenerateSpriteSheet = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuRawFolder = new javax.swing.JMenuItem();
        menuSourceFolder = new javax.swing.JMenuItem();
        menuClearOldFiles = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuColorChooser = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuRawFolder1 = new javax.swing.JMenuItem();
        menuSourceFolder1 = new javax.swing.JMenuItem();
        menuClearOldFiles1 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpriteSheet Maker");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enterPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enterPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("Set Raw Folder:");

        getRawFolder.setText("Select Folder");
        getRawFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRawFolderActionPerformed(evt);
            }
        });

        setRawFolder.setForeground(new java.awt.Color(255, 255, 255));
        setRawFolder.setText("First Select Raw Folder ....");
        setRawFolder.setMaximumSize(new java.awt.Dimension(860, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setRawFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getRawFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(setRawFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getRawFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setEnabled(false);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Sprite"));

        spriteDemoPanel.setPreferredSize(new java.awt.Dimension(274, 141));

        javax.swing.GroupLayout spriteDemoPanelLayout = new javax.swing.GroupLayout(spriteDemoPanel);
        spriteDemoPanel.setLayout(spriteDemoPanelLayout);
        spriteDemoPanelLayout.setHorizontalGroup(
            spriteDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spriteDemoPanelLayout.setVerticalGroup(
            spriteDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Padding:");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Sprite:");

        colorPadding.setEnabled(false);
        colorPadding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorPaddingActionPerformed(evt);
            }
        });

        colorSprite.setEnabled(false);
        colorSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSpriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorPadding, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(colorSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(colorPadding, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        spriteImageToggle.setText("Hide Image");
        spriteImageToggle.setEnabled(false);
        spriteImageToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteImageToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(spriteImageToggle)
                .addContainerGap())
            .addComponent(spriteDemoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(spriteDemoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spriteImageToggle))
        );

        finalSpritePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Spritesheet "));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Margins:");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Padding:");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Sprite:");

        colorMargin.setEnabled(false);
        colorMargin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorMarginActionPerformed(evt);
            }
        });

        colorPadding1.setEnabled(false);
        colorPadding1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorPadding1ActionPerformed(evt);
            }
        });

        colorSprite1.setEnabled(false);
        colorSprite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSprite1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(1, 1, 1)
                .addComponent(colorMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorPadding1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel34)
                        .addComponent(colorMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(colorPadding1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(colorSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout spriteDemoPanel2Layout = new javax.swing.GroupLayout(spriteDemoPanel2);
        spriteDemoPanel2.setLayout(spriteDemoPanel2Layout);
        spriteDemoPanel2Layout.setHorizontalGroup(
            spriteDemoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spriteDemoPanel2Layout.setVerticalGroup(
            spriteDemoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        spriteSheetImageToggle.setText("Show Image");
        spriteSheetImageToggle.setEnabled(false);
        spriteSheetImageToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteSheetImageToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout finalSpritePanelLayout = new javax.swing.GroupLayout(finalSpritePanel);
        finalSpritePanel.setLayout(finalSpritePanelLayout);
        finalSpritePanelLayout.setHorizontalGroup(
            finalSpritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(finalSpritePanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(spriteSheetImageToggle)
                .addContainerGap())
            .addComponent(spriteDemoPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        finalSpritePanelLayout.setVerticalGroup(
            finalSpritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalSpritePanelLayout.createSequentialGroup()
                .addComponent(spriteDemoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spriteSheetImageToggle))
        );

        sourceSpritePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Source Sprite"));

        javax.swing.GroupLayout sourceSpriteViewPanelLayout = new javax.swing.GroupLayout(sourceSpriteViewPanel);
        sourceSpriteViewPanel.setLayout(sourceSpriteViewPanelLayout);
        sourceSpriteViewPanelLayout.setHorizontalGroup(
            sourceSpriteViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        sourceSpriteViewPanelLayout.setVerticalGroup(
            sourceSpriteViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sourceSpritePanelLayout = new javax.swing.GroupLayout(sourceSpritePanel);
        sourceSpritePanel.setLayout(sourceSpritePanelLayout);
        sourceSpritePanelLayout.setHorizontalGroup(
            sourceSpritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sourceSpriteViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sourceSpritePanelLayout.setVerticalGroup(
            sourceSpritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sourceSpriteViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        finalSpriteSheetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Final SpriteSheet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout finalSpriteViewPanelLayout = new javax.swing.GroupLayout(finalSpriteViewPanel);
        finalSpriteViewPanel.setLayout(finalSpriteViewPanelLayout);
        finalSpriteViewPanelLayout.setHorizontalGroup(
            finalSpriteViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        finalSpriteViewPanelLayout.setVerticalGroup(
            finalSpriteViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout finalSpriteSheetPanelLayout = new javax.swing.GroupLayout(finalSpriteSheetPanel);
        finalSpriteSheetPanel.setLayout(finalSpriteSheetPanelLayout);
        finalSpriteSheetPanelLayout.setHorizontalGroup(
            finalSpriteSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalSpriteViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        finalSpriteSheetPanelLayout.setVerticalGroup(
            finalSpriteSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalSpriteViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sourceSpritePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalSpritePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalSpriteSheetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalSpriteSheetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sourceSpritePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(finalSpritePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setEnabled(false);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Top");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bottom");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Left");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Right");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Padding in every Image:");

        getPaddingRight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        getPaddingRight.setText("0");
        getPaddingRight.setEnabled(false);
        getPaddingRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        getPaddingBottom.setText("0");
        getPaddingBottom.setEnabled(false);
        getPaddingBottom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        getPaddingLeft.setText("0");
        getPaddingLeft.setEnabled(false);
        getPaddingLeft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        getPaddingTop.setText("0");
        getPaddingTop.setEnabled(false);
        getPaddingTop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        paddingType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Resize the Sprite", "Hide Overflow" }));
        paddingType.setEnabled(false);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Padding Type:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(getPaddingTop, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getPaddingBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getPaddingLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getPaddingRight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(paddingType, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(623, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(getPaddingRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getPaddingBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getPaddingLeft)
                    .addComponent(getPaddingTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paddingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Width");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Height");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Set Dimension of each Sprite:");

        getSpriteHeight.setText("0");
        getSpriteHeight.setEnabled(false);
        getSpriteHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        getSpriteWidth.setText("0");
        getSpriteWidth.setEnabled(false);
        getSpriteWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(getSpriteWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getSpriteHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(801, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(getSpriteHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getSpriteWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("How many Sprites in one row?");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Set Dimension of  SpriteSheet:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Sprites:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SpriteSheet Width:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SpriteSheet Height:");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Space between Sprites:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Right");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Bottom:");

        setTotalSprites.setEditable(false);
        setTotalSprites.setText("0");

        setSpritesheetWidth.setEditable(false);
        setSpritesheetWidth.setText("0");

        getSpriteRow.setText("0");
        getSpriteRow.setEnabled(false);
        getSpriteRow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        getSpriteSpaceLeft.setText("0");
        getSpriteSpaceLeft.setEnabled(false);
        getSpriteSpaceLeft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        getSpriteSpaceRight.setText("0");
        getSpriteSpaceRight.setEnabled(false);
        getSpriteSpaceRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChange(evt);
            }
        });

        setSpritesheetHeight.setEditable(false);
        setSpritesheetHeight.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addComponent(getSpriteRow, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTotalSprites, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setSpritesheetWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setSpritesheetHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getSpriteSpaceLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getSpriteSpaceRight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))
                        .addGap(0, 689, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(setTotalSprites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getSpriteRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(getSpriteSpaceLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getSpriteSpaceRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(setSpritesheetWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(setSpritesheetHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(633, 369));

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Image Type");

        getImageType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Alpha Detector" }));
        getImageType.setEnabled(false);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Select source folder:");

        setSourceFolder.setForeground(new java.awt.Color(255, 255, 255));
        setSourceFolder.setText("No folder selected");
        setSourceFolder.setMaximumSize(new java.awt.Dimension(352, 352));

        getSourceFolder.setText("Select");
        getSourceFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSourceFolderActionPerformed(evt);
            }
        });

        setGenerate.setText("Generate Spritesheet");
        setGenerate.setEnabled(false);
        setGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGenerateActionPerformed(evt);
            }
        });

        setSourceFiles.setBackground(new java.awt.Color(0, 0, 0));
        setSourceFiles.setForeground(new java.awt.Color(255, 255, 255));
        setSourceFiles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        setSourceFiles.setMaximumSize(new java.awt.Dimension(613, 177));
        setSourceFiles.setPreferredSize(new java.awt.Dimension(613, 1000));
        setSourceFiles.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(setSourceFiles);

        delItem.setText("Remove");
        delItem.setEnabled(false);
        delItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delItemActionPerformed(evt);
            }
        });

        applySprite.setText("Save & Apply to current Sprite");
        applySprite.setEnabled(false);
        applySprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applySpriteActionPerformed(evt);
            }
        });

        preview.setText("Preview");
        preview.setEnabled(false);
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        openRawFolder.setText("Open");
        openRawFolder.setEnabled(false);
        openRawFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRawFolderActionPerformed(evt);
            }
        });

        addFile.setText("Add");
        addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileActionPerformed(evt);
            }
        });

        clearFiles.setText("Clear");
        clearFiles.setEnabled(false);
        clearFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFilesActionPerformed(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(0, 0, 0));
        progressBar.setForeground(new java.awt.Color(255, 255, 255));
        progressBar.setToolTipText("Progress");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Importing Type:");

        importType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selected Folder", "Inner Folder" }));

        spriteSheetCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        spriteSheetCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        spriteSheetCheckBox.setSelected(true);
        spriteSheetCheckBox.setText("Spritesheet");
        spriteSheetCheckBox.setEnabled(false);

        finalSpriteSheetCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        finalSpriteSheetCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        finalSpriteSheetCheckBox.setText("Final Spritesheet");
        finalSpriteSheetCheckBox.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getImageType, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(importType, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(spriteSheetCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(finalSpriteSheetCheckBox)))
                        .addGap(18, 18, 18)
                        .addComponent(applySprite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearFiles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setSourceFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getSourceFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openRawFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getImageType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(importType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(setSourceFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getSourceFolder)
                    .addComponent(openRawFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(applySprite, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spriteSheetCheckBox)
                            .addComponent(finalSpriteSheetCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(preview)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearFiles)
                            .addComponent(delItem)
                            .addComponent(addFile)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );

        jMenu1.setText("File");

        menuAddFromFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuAddFromFolder.setText("Add From Folder");
        menuAddFromFolder.setEnabled(false);
        menuAddFromFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddFromFolderActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddFromFolder);

        menuAddFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuAddFile.setText("Add File");
        menuAddFile.setEnabled(false);
        menuAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddFileActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddFile);

        menuLoadOldFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuLoadOldFiles.setText("Load Old Files");
        menuLoadOldFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadOldFilesActionPerformed(evt);
            }
        });
        jMenu1.add(menuLoadOldFiles);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuEditFileProperties.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuEditFileProperties.setText("Edit File Properties");
        menuEditFileProperties.setEnabled(false);
        menuEditFileProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditFilePropertiesActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditFileProperties);

        menuToggleImageType.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuToggleImageType.setText("Toggle Image Type");
        menuToggleImageType.setEnabled(false);
        menuToggleImageType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuToggleImageTypeActionPerformed(evt);
            }
        });
        jMenu2.add(menuToggleImageType);

        menuTogglePaddingType.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuTogglePaddingType.setText("Toggle PaddingType");
        menuTogglePaddingType.setEnabled(false);
        menuTogglePaddingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTogglePaddingTypeActionPerformed(evt);
            }
        });
        jMenu2.add(menuTogglePaddingType);

        menuToggleImportType.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuToggleImportType.setText("Toggle Import Type");
        menuToggleImportType.setEnabled(false);
        menuToggleImportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuToggleImportTypeActionPerformed(evt);
            }
        });
        jMenu2.add(menuToggleImportType);

        menuRemoveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuRemoveFile.setText("Remove File");
        menuRemoveFile.setEnabled(false);
        menuRemoveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveFileActionPerformed(evt);
            }
        });
        jMenu2.add(menuRemoveFile);

        menuClearAllFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuClearAllFile.setText("Clear All File");
        menuClearAllFile.setEnabled(false);
        menuClearAllFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearAllFileActionPerformed(evt);
            }
        });
        jMenu2.add(menuClearAllFile);

        menuShowImage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuShowImage.setText("Show Image");
        menuShowImage.setEnabled(false);
        menuShowImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShowImageActionPerformed(evt);
            }
        });
        jMenu2.add(menuShowImage);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Run");

        menuApplyToSprite.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuApplyToSprite.setText("Apply to sprite");
        menuApplyToSprite.setEnabled(false);
        menuApplyToSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuApplyToSpriteActionPerformed(evt);
            }
        });
        jMenu3.add(menuApplyToSprite);

        menuPriview.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuPriview.setText("Preview");
        menuPriview.setEnabled(false);
        menuPriview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPriviewActionPerformed(evt);
            }
        });
        jMenu3.add(menuPriview);

        menuGenerateSpriteSheet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuGenerateSpriteSheet.setText("Generate SpriteSheet");
        menuGenerateSpriteSheet.setEnabled(false);
        menuGenerateSpriteSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerateSpriteSheetActionPerformed(evt);
            }
        });
        jMenu3.add(menuGenerateSpriteSheet);

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Enable ");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Settings");

        menuRawFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuRawFolder.setText("Raw Folder");
        menuRawFolder.setEnabled(false);
        menuRawFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRawFolderActionPerformed(evt);
            }
        });
        jMenu4.add(menuRawFolder);

        menuSourceFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuSourceFolder.setText("Source Folder");
        menuSourceFolder.setEnabled(false);
        menuSourceFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSourceFolderActionPerformed(evt);
            }
        });
        jMenu4.add(menuSourceFolder);

        menuClearOldFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuClearOldFiles.setText("Clear Old Files");
        menuClearOldFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearOldFilesActionPerformed(evt);
            }
        });
        jMenu4.add(menuClearOldFiles);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Reset Data");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menuColorChooser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuColorChooser.setText("Change Color");
        menuColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorChooserActionPerformed(evt);
            }
        });
        jMenu4.add(menuColorChooser);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Others");

        menuRawFolder1.setText("Help");
        menuRawFolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRawFolder1ActionPerformed(evt);
            }
        });
        jMenu6.add(menuRawFolder1);

        menuSourceFolder1.setText("About");
        menuSourceFolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSourceFolder1ActionPerformed(evt);
            }
        });
        jMenu6.add(menuSourceFolder1);

        menuClearOldFiles1.setText("Contact");
        menuClearOldFiles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearOldFiles1ActionPerformed(evt);
            }
        });
        jMenu6.add(menuClearOldFiles1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getRawFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRawFolderActionPerformed
        // TODO add your handling code here:
        backView.rawFolderClicked();
    }//GEN-LAST:event_getRawFolderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void getSourceFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSourceFolderActionPerformed
        // TODO add your handling code here:
        backView.sourceFolderClicked();
    }//GEN-LAST:event_getSourceFolderActionPerformed

    private void onChange(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onChange
        // TODO add your handling code here:
        backView.onChange();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        backView.onPreviewClicked();
        }
    }//GEN-LAST:event_onChange

    private void delItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delItemActionPerformed
        // TODO add your handling code here:
        backView.delItem(0);
    }//GEN-LAST:event_delItemActionPerformed

    private void applySpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applySpriteActionPerformed
        // TODO add your handling code here:
        backView.applyToSprite();
    }//GEN-LAST:event_applySpriteActionPerformed

    private void openRawFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRawFolderActionPerformed
        // TODO add your handling code here:
        backView.openRawFolder();
    }//GEN-LAST:event_openRawFolderActionPerformed

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        // TODO add your handling code here:
        backView.onPreviewClicked();
    }//GEN-LAST:event_previewActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void setGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGenerateActionPerformed
        // TODO add your handling code here:
        backView.saveTheSpriteSheet();
    }//GEN-LAST:event_setGenerateActionPerformed

    private void spriteImageToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteImageToggleActionPerformed
        // TODO add your handling code here:
        backView.spriteImageToggle();
    }//GEN-LAST:event_spriteImageToggleActionPerformed

    private void addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileActionPerformed
        // TODO add your handling code here:
        backView.addFile();
    }//GEN-LAST:event_addFileActionPerformed

    private void clearFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFilesActionPerformed
        // TODO add your handling code here:
        backView.clearFiles();
    }//GEN-LAST:event_clearFilesActionPerformed

    private void menuAddFromFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddFromFolderActionPerformed
        // TODO add your handling code here:
        backView.menu.sourceFolder();
    }//GEN-LAST:event_menuAddFromFolderActionPerformed

    private void menuAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddFileActionPerformed
        // TODO add your handling code here:
        backView.menu.mAddFile();
    }//GEN-LAST:event_menuAddFileActionPerformed

    private void menuEditFilePropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditFilePropertiesActionPerformed
        // TODO add your handling code here:
        backView.menu.onListItemDoubleClick();
    }//GEN-LAST:event_menuEditFilePropertiesActionPerformed

    private void menuToggleImageTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToggleImageTypeActionPerformed
        // TODO add your handling code here:
        backView.menu.toggleImageType();
    }//GEN-LAST:event_menuToggleImageTypeActionPerformed

    private void menuTogglePaddingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTogglePaddingTypeActionPerformed
        // TODO add your handling code here:
        backView.menu.togglePaddingType();
    }//GEN-LAST:event_menuTogglePaddingTypeActionPerformed

    private void menuToggleImportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToggleImportTypeActionPerformed
        // TODO add your handling code here:
        backView.menu.toggleImportType();
    }//GEN-LAST:event_menuToggleImportTypeActionPerformed

    private void menuApplyToSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuApplyToSpriteActionPerformed
        // TODO add your handling code here:
        backView.menu.mApplyToSprite();
    }//GEN-LAST:event_menuApplyToSpriteActionPerformed

    private void menuPriviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPriviewActionPerformed
        // TODO add your handling code here:
        backView.menu.priview();
    }//GEN-LAST:event_menuPriviewActionPerformed

    private void menuGenerateSpriteSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerateSpriteSheetActionPerformed
        // TODO add your handling code here:
        backView.menu.generateSpriteSheet();
    }//GEN-LAST:event_menuGenerateSpriteSheetActionPerformed

    private void menuRawFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRawFolderActionPerformed
        // TODO add your handling code here:
        backView.menu.rawFolder();
    }//GEN-LAST:event_menuRawFolderActionPerformed

    private void menuSourceFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSourceFolderActionPerformed
        // TODO add your handling code here:
        backView.menu.mSourceFolder();
    }//GEN-LAST:event_menuSourceFolderActionPerformed

    private void menuRemoveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveFileActionPerformed
        // TODO add your handling code here:
        backView.menu.removeFile();
    }//GEN-LAST:event_menuRemoveFileActionPerformed

    private void menuClearAllFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearAllFileActionPerformed
        // TODO add your handling code here:
        backView.menu.clearAllFiles();
    }//GEN-LAST:event_menuClearAllFileActionPerformed

    private void menuShowImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShowImageActionPerformed
        // TODO add your handling code here:
        backView.menu.showImage();
    }//GEN-LAST:event_menuShowImageActionPerformed

    private void menuLoadOldFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadOldFilesActionPerformed
        // TODO add your handling code here:
        backView.menu.loadOldFiles();
    }//GEN-LAST:event_menuLoadOldFilesActionPerformed

    private void menuClearOldFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearOldFilesActionPerformed
        // TODO add your handling code here:
        backView.menu.clearOldItem();
    }//GEN-LAST:event_menuClearOldFilesActionPerformed

    private void spriteSheetImageToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteSheetImageToggleActionPerformed
        // TODO add your handling code here:
        backView.spriteSheetImageToggle();
    }//GEN-LAST:event_spriteSheetImageToggleActionPerformed

    private void enterPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterPressed
        // TODO add your handling code here:
      System.out.println("key pressed");
    }//GEN-LAST:event_enterPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        backView.resetInfo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuSourceFolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSourceFolder1ActionPerformed
        // TODO add your handling code here:
       javax.swing.JOptionPane.showMessageDialog(this,"SpriteSheet Maker is Software which helps to make \nSpriteSheet used in Game Development or Website Development"
                , "SpriteSheet Maker v1.0 ",JOptionPane.PLAIN_MESSAGE);
     
    }//GEN-LAST:event_menuSourceFolder1ActionPerformed

    private void menuClearOldFiles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearOldFiles1ActionPerformed
        // TODO add your handling code here:
         int x =  javax.swing.JOptionPane.showConfirmDialog(this, "Do You want to Contact Developer Website for any feedback?");
         if(x == 0){
            if(Desktop.isDesktopSupported()){
                 try {
                    try {
                        Desktop.getDesktop().browse(new URI("http://www.samundrakc.com.np"));
                    } catch (IOException ex) {
                        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                 } catch (URISyntaxException ex) {
                     Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                 }
            }
         }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Please Visit http://www.samundrakc.com.np for feedback and suggestion");
         }
    }//GEN-LAST:event_menuClearOldFiles1ActionPerformed

    private void menuColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorChooserActionPerformed
        // TODO add your handling code here:
        backView.menu.colorChooser("");
    }//GEN-LAST:event_menuColorChooserActionPerformed

    private void colorPaddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPaddingActionPerformed
        // TODO add your handling code here:
        backView.menu.colorChooser("padding");
    }//GEN-LAST:event_colorPaddingActionPerformed

    private void colorSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSpriteActionPerformed
        // TODO add your handling code here:
        backView.menu.colorChooser("sprite");
    }//GEN-LAST:event_colorSpriteActionPerformed

    private void colorMarginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorMarginActionPerformed
        // TODO add your handling code here:
        backView.menu.colorChooser("margin");
    }//GEN-LAST:event_colorMarginActionPerformed

    private void colorPadding1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPadding1ActionPerformed
        // TODO add your handling code here:
        backView.menu.colorChooser("padding");
    }//GEN-LAST:event_colorPadding1ActionPerformed

    private void colorSprite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSprite1ActionPerformed
        // TODO add your handling code here:
        backView.menu.colorChooser("sprite");
    }//GEN-LAST:event_colorSprite1ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        backView.menu.enableComponent();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void menuRawFolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRawFolder1ActionPerformed
        // TODO add your handling code here:
        int x =  javax.swing.JOptionPane.showConfirmDialog(this, "Do You want to visit Developer Website for help?");
        if(x == 0){
            if(Desktop.isDesktopSupported()){
                try {
                    try {
                        Desktop.getDesktop().browse(new URI("http://www.samundrakc.com.np"));
                    } catch (IOException ex) {
                        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (URISyntaxException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Please Visit http://www.samundrakc.com.np for more help");
        }
    }//GEN-LAST:event_menuRawFolder1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addFile;
    public javax.swing.JButton applySprite;
    public javax.swing.JButton clearFiles;
    public javax.swing.JButton colorMargin;
    public javax.swing.JButton colorPadding;
    public javax.swing.JButton colorPadding1;
    public javax.swing.JButton colorSprite;
    public javax.swing.JButton colorSprite1;
    public javax.swing.JButton delItem;
    public javax.swing.JPanel finalSpritePanel;
    public javax.swing.JCheckBox finalSpriteSheetCheckBox;
    public javax.swing.JPanel finalSpriteSheetPanel;
    public javax.swing.JPanel finalSpriteViewPanel;
    public javax.swing.JComboBox getImageType;
    public javax.swing.JFormattedTextField getPaddingBottom;
    public javax.swing.JFormattedTextField getPaddingLeft;
    public javax.swing.JFormattedTextField getPaddingRight;
    public javax.swing.JFormattedTextField getPaddingTop;
    public javax.swing.JButton getRawFolder;
    public javax.swing.JButton getSourceFolder;
    public javax.swing.JFormattedTextField getSpriteHeight;
    public javax.swing.JFormattedTextField getSpriteRow;
    public javax.swing.JFormattedTextField getSpriteSpaceLeft;
    public javax.swing.JFormattedTextField getSpriteSpaceRight;
    public javax.swing.JFormattedTextField getSpriteWidth;
    public javax.swing.JComboBox importType;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JMenuItem menuAddFile;
    public javax.swing.JMenuItem menuAddFromFolder;
    public javax.swing.JMenuItem menuApplyToSprite;
    public javax.swing.JMenuItem menuClearAllFile;
    private javax.swing.JMenuItem menuClearOldFiles;
    private javax.swing.JMenuItem menuClearOldFiles1;
    public javax.swing.JMenuItem menuColorChooser;
    public javax.swing.JMenuItem menuEditFileProperties;
    private javax.swing.JMenuItem menuExit;
    public javax.swing.JMenuItem menuGenerateSpriteSheet;
    private javax.swing.JMenuItem menuLoadOldFiles;
    public javax.swing.JMenuItem menuPriview;
    public javax.swing.JMenuItem menuRawFolder;
    private javax.swing.JMenuItem menuRawFolder1;
    public javax.swing.JMenuItem menuRemoveFile;
    public javax.swing.JMenuItem menuShowImage;
    public javax.swing.JMenuItem menuSourceFolder;
    public javax.swing.JMenuItem menuSourceFolder1;
    public javax.swing.JMenuItem menuToggleImageType;
    public javax.swing.JMenuItem menuToggleImportType;
    public javax.swing.JMenuItem menuTogglePaddingType;
    public javax.swing.JButton openRawFolder;
    public javax.swing.JComboBox paddingType;
    public javax.swing.JButton preview;
    public static javax.swing.JProgressBar progressBar;
    public javax.swing.JButton setGenerate;
    public javax.swing.JLabel setRawFolder;
    public static javax.swing.JList setSourceFiles;
    public javax.swing.JLabel setSourceFolder;
    public javax.swing.JFormattedTextField setSpritesheetHeight;
    public javax.swing.JFormattedTextField setSpritesheetWidth;
    public javax.swing.JFormattedTextField setTotalSprites;
    public javax.swing.JPanel sourceSpritePanel;
    public javax.swing.JPanel sourceSpriteViewPanel;
    public javax.swing.JPanel spriteDemoPanel;
    public javax.swing.JPanel spriteDemoPanel2;
    public javax.swing.JToggleButton spriteImageToggle;
    public javax.swing.JCheckBox spriteSheetCheckBox;
    public javax.swing.JToggleButton spriteSheetImageToggle;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        try {
            ArrayList<BufferedImage> images = new ArrayList<BufferedImage>();
            images.add(ImageIO.read(getClass().getResource("16x16.png")));
            images.add(ImageIO.read(getClass().getResource("32x32.png")));
            images.add(ImageIO.read(getClass().getResource("64x64.png")));
            images.add(ImageIO.read(getClass().getResource("128x128.png")));
            setIconImages(images);
         
            //  setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("spriteSheetMakerLogo.png")));
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
 

}
